{% set name = "xorg-libxfont2" %}
{% set version = "2.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.freedesktop.org/xorg/lib/libxfont/-/archive/libXfont2-{{ version }}/libxfont-libXfont2-{{ version }}.tar.gz
  sha256: 37979d32c9b59e33165347eb8f428951796e5ab94006c86edf2c0c9db06d2a0a

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - pkg-config
    - automake
    - autoconf
    - libtool
    - make
    - xorg-util-macros
  host:
    - freetype 2.13.3
    - fontconfig 2.15.0
    - zlib {{ zlib }}
    - xorg-xorgproto 2024.1
    - xorg-xtrans 1.6.0
    - xorg-libfontenc 1.1.8
  run:
    - freetype
    - fontconfig
    - zlib
    - xorg-xorgproto
    - xorg-xtrans
    - xorg-libfontenc

test:
  requires:
    - pkg-config
  commands:
    - test -f $PREFIX/lib/libXfont2.dylib  # [osx]
    - test -f $PREFIX/lib/libXfont2.so     # [linux]
    - pkg-config --exists xfont2

about:
  home: https://gitlab.freedesktop.org/xorg/lib/libxfont
  summary: X font file parsing and rasterizing library used by the X server
  description: |
    libXfont2 provides the core of the legacy X11 font system, handling
    font file parsing and rendering for the X server and Xvfb.
  license: MIT
  license_family: MIT
  license_file: COPYING
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libxfont
  doc_url: https://www.x.org/wiki/Documentation/

extra:
  recipe-maintainers:
    - elundby
    - ViridianMelody